/* Writes config.js from environment variables at build time.
 *
 * Netlify runs this via the build command in netlify.toml. Locally you can
 * run it too, after setting the same variables in your shell — or just hand-
 * write config.js from config.example.js.
 *
 * Note: these values are NOT secrets. Firebase web config is public by design
 * and ends up readable in the browser no matter how it is delivered. Keeping it
 * in env vars only keeps it out of the git repo. What actually protects your
 * data is Firestore Security Rules plus API key restrictions.
 */
const fs = require('fs');
const path = require('path');

const KEYS = {
  apiKey:            'FIREBASE_API_KEY',
  authDomain:        'FIREBASE_AUTH_DOMAIN',
  projectId:         'FIREBASE_PROJECT_ID',
  storageBucket:     'FIREBASE_STORAGE_BUCKET',
  messagingSenderId: 'FIREBASE_MESSAGING_SENDER_ID',
  appId:             'FIREBASE_APP_ID',
};

const config = {};
const missing = [];
for (const [field, envName] of Object.entries(KEYS)) {
  const value = process.env[envName];
  if (value) config[field] = value;
  else missing.push(envName);
}

const out = path.join(__dirname, 'config.js');

if (missing.length) {
  console.warn('generate-config: missing ' + missing.join(', '));
  console.warn('generate-config: writing placeholder config — app will run in guest mode.');
  fs.writeFileSync(out, 'window.GHARSEVA_CONFIG = null;\n');
  process.exit(0);
}

fs.writeFileSync(out,
  '/* Generated by generate-config.js - do not edit, do not commit. */\n' +
  'window.GHARSEVA_CONFIG = ' + JSON.stringify(config, null, 2) + ';\n'
);
console.log('generate-config: wrote config.js for project ' + config.projectId);
